name       : opencsg
version    : 1.4.2
release    : 3
source     :
    - http://www.opencsg.org/OpenCSG-1.4.2.tar.gz : d952ec5d3a2e46a30019c210963fcddff66813efc9c29603b72f9553adff4afb
license    : GPL-2.0
component  : programming
summary    : OpenCSG is a library that does image-based CSG rendering using OpenGL
description: |
    OpenCSG is a library that does image-based CSG rendering using OpenGL
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glut)
    - pkgconfig(QtCore)
setup      : |
    sed -i "s|/local||g" example/Makefile src/Makefile
    sed -i -e "s|CFLAGS.*=|CFLAGS ?=|g" example/Makefile src/Makefile
    sed -i -e "s|CXXFLAGS.*=|CXXFLAGS ?=|g" example/Makefile src/Makefile
build      : |
    %make -j1
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -rf $installdir/usr/bin
